### ISSUE TITLE
report all traceableRequests in results-code graph, not just last one.

### ISSUE THREAD

**Issue by rnewson** [benschmaus/nodeload#1]
Hi,

I have a requestLoop that does a PUT followed by a GET, but only the '200' result code is populated in the graph. I'm reading the code as I suspect I can fix it, but just wanted you to know about this issue.

**Comment by rnewson** [comment]
I think it's an artifact of the wrapping. loopWrapper appears to only fire at each iteration, so requests made in the middle of the function escape being recorded. yes?

**Comment by jonjlee** [comment]
Yes, this is as designed. This gives you freedom to do whatever you want within an iteration of the requestLoop without affecting the stats.  Everything within one iteration is considered a single transaction, which is what is timed.  If you issue multiple HTTP requests in a single iteration of the requestLoop and want to time each of them, you can break it up into separate tests if possible. Or you can grab the statistics objects from the return value of addTest() and write to it directly [i.e. addTest().stats['latency'].put(latency)].

**Comment by rnewson** [comment]
Makes sense, thanks.

What I did was add an empty array and push the subsequent request into it and then on the next call, if the array is not empty, return the first item from it. This is because my second operation depends on the first (the PUT returns an ETag which I need to pass in If-Match to update it successfully: CouchDB).
