### ISSUE TITLE
nodeload in npm repo is old

### ISSUE THREAD

**Issue by ghost** [benschmaus/nodeload#11]
The version of npm that gets installed with 'npm install nodeload' is considerably different from the latest code.  Kind of confusing, especially when first approaching this library.  The new code is way better :)

**Comment by benschmaus** [comment]
Hi, recursivevirus.  I just published nodeload v0.4.0 to npm.  Thanks for the heads-up!

**Comment by ghost** [comment]
Awesome, I'll check it out.
Thanks!
Hernan

On Feb 3, 2012, at 7:23 PM, Benjamin Schmaus
reply@reply.github.com
wrote:
