### ISSUE TITLE
nl.js doesn't support query strings?

### ISSUE THREAD

**Issue by dropwhile** [benschmaus/nodeload#5]
When I use a command like this

```
nl.js -c 100 -n 4000 -i 1 'http://127.0.0.1:3000/api?q=test'
```

Nodeload does not use the query string in the resulting test (verified by server logs).
Is this expected behavior?

**Comment by jonjlee** [comment]
cactus, thanks for reporting this!  This is definitely a bug. In lib/options.js, we're using url.parse(), and saving only the pathname.  This discards both the query string and hash. We should instead be taking everything after host & port.

I'll patch this as soon as possible.  In the meantime, you might consider using a separate generator file (like examples/test-generator.js).  I know it's a heavy weight solution for the simple bug, but it'll get you around the issue immediately.

**Comment by dropwhile** [comment]
Thanks for the quick response, and for providing a pointer to a work-around.
:)

**Comment by danmilon** [comment]
Hello. I'm affected by that bug.
It is not much of a hassle to fix this right? If i provide a patch you'll commit?

Thanks ;)

**Comment by dropwhile** [comment]
old
