### ISSUE TITLE
HTTP_PORT environment variable needs clearer documentation

### ISSUE THREAD

**Issue by fabware** [benschmaus/nodeload#7]
nodeload needs listen on a specific http port, the default is 8000, which can be configured with HTTP_PORT environment. I happened have another server listened on 8000, it makes nodeload unable to start, showing ADDRESS ALREADY IN USE. 

It getting me look at the source code to figure out what's going wrong. I think this HTTP_PORT should be highlighted in the documentation.

**Comment by jonjlee** [comment]
Thanks for the comment -- you're absolutely right. The docs need quite a bit of work right now, and I'll be sure to call that out in a config section on the main README.  Also, you've probably seen this already, but you can also configure the port in code using require('nodeload').usePort(...).

**Comment by fabware** [comment]
Thanks for your reply. nodeload.usePort(...) works great.
